const Joi = require('@hapi/joi')

const schema = Joi.object().keys({
  year: Joi.number().required(),
  month: Joi.number().required(),
  day: Joi.number().required(),
  dayOfWeek: Joi.number().required(),
  airlineId: Joi.string().required(),
  airlineName: Joi.string().required(),
  flightNumber: Joi.number().required(),
  tailNumber: Joi.string().required(),
  originAirport: Joi.string().required(),
  originAirportName: Joi.string().required(),
  originAirportCity: Joi.string().required(),
  originAirportState: Joi.string().required(),
  originAirportCountry: Joi.string().required(),
  originAirportLatitude: Joi.number().required(),
  originAirportLongitude: Joi.number().required(),
  destinationAirport: Joi.string().required(),
  destinationAirportName: Joi.string().required(),
  destinationAirportCity: Joi.string().required(),
  destinationAirportState: Joi.string().required(),
  destinationAirportCountry: Joi.string().required(),
  destinationAirportLatitude: Joi.number().required(),
  destinationAirportLongitude: Joi.number().required(),
  departureTime: Joi.number().required(),
  scheduledDepartureTime: Joi.number().required(),
  departureDelayInMinutes: Joi.number().required(),
  taxiOutDurationInMinutes: Joi.number().required(),
  wheelsOff: Joi.number().required(),
  durationInMinutes: Joi.number().required(),
  scheduledDurationInMinutes: Joi.number().required(),
  airTimeInMinutes: Joi.number().required(),
  distance: Joi.number().required(),
  wheelsOn: Joi.number().required(),
  taxiInDurationInMinutes: Joi.number().required(),
  arrivalTime: Joi.number().required(),
  scheduledArrivalTime: Joi.number().required(),
  arrivalDelayInMinutes: Joi.number().required(),
  diverted: Joi.number().required(),
  cancelled: Joi.number().required(),
  cancellationReason: Joi.string().allow('').required(),
  airSystemDelayInMinutes: Joi.number().required(),
  securityDelayInMinutes: Joi.number().required(),
  lateAircraftDelayInMinutes: Joi.number().required(),
  weatherDelayInMinutes: Joi.number().required(),
  sentTimestamp: Joi.number().required()
})

module.exports = schema
